# Name of the workflow
name: Deploy new version

# Define the trigger event(s)
# Only deploy when a new tag is pushed ('push:tags:') or manually (with 'workflow_dispatch:')
# If pushing tag, it has to match "v*.*.*"
on:
    workflow_dispatch:
    push:
        tags:
          - "v*.*.*"
          
# Must match the project() name in CMakeLists.txt, variable used below to copy .hex file
env:
    APP_NAME: TSM_PicoW_Blinky
    
# Allow this workflow to write back to the repository
permissions:
    contents: write

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  # Job to print something out
  # say-hello:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Say hello
  #      run: echo "Hello, GitHub Actions!"

  # Build binary and send to releases
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: copy Dockerfile for this job
        run: cp .github/Dockerfile .

      - name: Build Docker image
        run: docker build -t tsmcicd-image .
        
      - name: Create Docker container
        run: docker create --name tsmcicd-container tsmcicd-image
        
      - name: Copy out .uf2 file
        run: docker cp tsmcicd-container:/project/build/Release/${APP_NAME}.uf2 ./${APP_NAME}.uf2
        
      - name: Put environment variable into the env context
        run: echo "app_name=$APP_NAME" >> $GITHUB_ENV
        
        # for the push, we need the tag! This step is skipped if we run it manually
      - name: Push to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: ${{ env.app_name }}.uf2
            body_path: CHANGELOG.md

